package com.mazkiplay.nusantara;

import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.text.*; import java.util.*;

public class ForexAgent {
 public static class Candle{public long time;public double open,high,low,close,volume;Candle(long t,double o,double h,double l,double c,double v){time=t;open=o;high=h;low=l;close=c;volume=v;}}
 public static class News{public String title,link,source,pubDate;News(String t,String l,String s,String d){title=t;link=l;source=s;pubDate=d;}}
 public static class Snapshot{public String pair,interval,asOf,trend,signal,setup,rationale;public ArrayList<Candle> candles=new ArrayList<>();public ArrayList<News> news=new ArrayList<>();public double price,rsi,ema20,ema50,ema200,bbUpper,bbMid,bbLower,atr,support,resistance,fib382,fib50,fib618,entry,sl,tp1,tp2,riskPct,positionUnits,confidence;public int bullish,bearish;public boolean marketDataLive;}
 public static Snapshot analyze(String pair,String interval,String style,double capital,double riskPct)throws Exception{
  Snapshot s=new Snapshot();s.pair=pair;s.interval=interval;s.candles=fetchCandles(pair.replace("/","")+"=X",interval,rangeFor(interval));if(s.candles.size()<60)throw new Exception("Data candle tidak cukup.");s.marketDataLive=true;s.price=s.candles.get(s.candles.size()-1).close;
  s.rsi=rsi(s.candles,14);s.ema20=ema(s.candles,20);s.ema50=ema(s.candles,50);s.ema200=ema(s.candles,Math.min(200,s.candles.size()));double[] bb=bollinger(s.candles,20,2);s.bbUpper=bb[0];s.bbMid=bb[1];s.bbLower=bb[2];s.atr=atr(s.candles,14);double[] sr=sr(s.candles,60);s.support=sr[0];s.resistance=sr[1];double span=s.resistance-s.support;s.fib382=s.resistance-span*.382;s.fib50=s.resistance-span*.5;s.fib618=s.resistance-span*.618;s.trend=trend(s);
  if(s.price>s.ema20)s.bullish++;else s.bearish++;if(s.ema20>s.ema50)s.bullish++;else s.bearish++;if(s.ema50>s.ema200)s.bullish++;else s.bearish++;if(s.rsi>50&&s.rsi<70)s.bullish++;else if(s.rsi<50&&s.rsi>30)s.bearish++;if(s.price>s.bbMid)s.bullish++;else s.bearish++;
  if(Math.abs(s.price-s.support)<s.atr*1.2)s.bullish+=2;if(Math.abs(s.price-s.resistance)<s.atr*1.2)s.bearish+=2;boolean buy=s.bullish>s.bearish;s.signal=buy?"BUY":"SELL";double buffer=Math.max(s.atr*1.2,span*.08);s.entry=s.price;s.sl=buy?s.price-buffer:s.price+buffer;double risk=Math.abs(s.entry-s.sl);s.tp1=buy?s.entry+risk*2:s.entry-risk*2;s.tp2=buy?s.entry+risk*3:s.entry-risk*3;s.riskPct=Math.max(.25,Math.min(2,riskPct));s.positionUnits=risk>0?(capital*s.riskPct/100)/risk:0;s.confidence=Math.min(95,55+Math.abs(s.bullish-s.bearish)*6);s.setup=setup(s);s.news=fetchNews(pair);s.rationale=buildRationale(s,style);s.asOf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss XXX",Locale.US).format(new Date());return s;
 }
 private static String rangeFor(String i){if(i.contains("m"))return"5d";if(i.contains("h"))return"1mo";if(i.equals("1d"))return"2y";return"5d";}
 public static ArrayList<Candle> fetchCandles(String symbol,String interval,String range)throws Exception{String u="https://query1.finance.yahoo.com/v8/finance/chart/"+URLEncoder.encode(symbol,"UTF-8")+"?interval="+interval+"&range="+range+"&includePrePost=false";JSONObject r=new JSONObject(get(u)).getJSONObject("chart").getJSONArray("result").getJSONObject(0);JSONArray ts=r.getJSONArray("timestamp"),o=r.getJSONObject("indicators").getJSONArray("quote").getJSONObject(0).getJSONArray("open"),h=r.getJSONObject("indicators").getJSONArray("quote").getJSONObject(0).getJSONArray("high"),l=r.getJSONObject("indicators").getJSONArray("quote").getJSONObject(0).getJSONArray("low"),c=r.getJSONObject("indicators").getJSONArray("quote").getJSONObject(0).getJSONArray("close"),v=r.getJSONObject("indicators").getJSONArray("quote").getJSONObject(0).optJSONArray("volume");ArrayList<Candle>a=new ArrayList<>();for(int i=0;i<ts.length();i++)if(!o.isNull(i)&&!h.isNull(i)&&!l.isNull(i)&&!c.isNull(i))a.add(new Candle(ts.getLong(i),o.getDouble(i),h.getDouble(i),l.getDouble(i),c.getDouble(i),v==null||v.isNull(i)?0:v.getDouble(i)));return a;}
 public static ArrayList<News> fetchNews(String pair){ArrayList<News> out=new ArrayList<>();try{String u="https://news.google.com/rss/search?q="+URLEncoder.encode(pair+" forex macroeconomics","UTF-8")+"&hl=en-US&gl=US&ceid=US:en";String x=get(u);int p=0;while(out.size()<10){int a=x.indexOf("<item>",p),b=x.indexOf("</item>",a);if(a<0||b<0)break;String z=x.substring(a,b);out.add(new News(tag(z,"title"),tag(z,"link"),"Public news RSS",tag(z,"pubDate")));p=b+7;}}catch(Exception ignored){}return out;}
 private static String tag(String x,String t){int a=x.indexOf("<"+t+">"),b=x.indexOf("</"+t+">",a);return a<0||b<0?"":x.substring(a+t.length()+2,b).replace("&amp;","&").replace("&quot;","\"");}
 private static String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestProperty("User-Agent","Nusantara-Agent/0.3");int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();if(in==null)throw new IOException("HTTP "+code);BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String z;while((z=r.readLine())!=null)s.append(z);if(code>=300)throw new IOException("HTTP "+code);return s.toString();}
 public static double ema(ArrayList<Candle>a,int n){double k=2.0/(n+1),e=a.get(0).close;for(int i=1;i<a.size();i++)e=a.get(i).close*k+e*(1-k);return e;}
 public static double rsi(ArrayList<Candle>a,int n){double g=0,l=0;for(int i=1;i<=n;i++){double d=a.get(i).close-a.get(i-1).close;if(d>0)g+=d;else l-=d;}g/=n;l/=n;for(int i=n+1;i<a.size();i++){double d=a.get(i).close-a.get(i-1).close;g=(g*(n-1)+Math.max(0,d))/n;l=(l*(n-1)+Math.max(0,-d))/n;}return l==0?100:100-(100/(1+g/l));}
 public static double[] bollinger(ArrayList<Candle>a,int n,double m){int st=Math.max(0,a.size()-n);double x=0;for(int i=st;i<a.size();i++)x+=a.get(i).close;x/=a.size()-st;double v=0;for(int i=st;i<a.size();i++){double d=a.get(i).close-x;v+=d*d;}double sd=Math.sqrt(v/(a.size()-st));return new double[]{x+m*sd,x,x-m*sd};}
 public static double atr(ArrayList<Candle>a,int n){int st=Math.max(1,a.size()-n);double x=0;for(int i=st;i<a.size();i++){Candle c=a.get(i),p=a.get(i-1);x+=Math.max(c.high-c.low,Math.max(Math.abs(c.high-p.close),Math.abs(c.low-p.close)));}return x/(a.size()-st);}
 private static double[] sr(ArrayList<Candle>a,int n){int st=Math.max(0,a.size()-n);double lo=Double.MAX_VALUE,hi=-Double.MAX_VALUE;for(int i=st;i<a.size();i++){lo=Math.min(lo,a.get(i).low);hi=Math.max(hi,a.get(i).high);}return new double[]{lo,hi};}
 private static String trend(Snapshot s){if(s.ema20>s.ema50&&s.ema50>s.ema200)return"STRONG BULLISH";if(s.ema20<s.ema50&&s.ema50<s.ema200)return"STRONG BEARISH";return s.ema20>s.ema50?"BULLISH BIAS":"BEARISH BIAS";}
 private static String setup(Snapshot s){if(Math.abs(s.price-s.fib50)<s.atr)return"Fibonacci 50% reaction zone";if(Math.abs(s.price-s.bbMid)<s.atr)return"Bollinger mid-band retest";if(s.rsi<35)return"RSI oversold watch";if(s.rsi>65)return"RSI overbought watch";return"Trend continuation / pullback";}
 private static String buildRationale(Snapshot s,String style){return"Mode="+style+" | MTF: gunakan timeframe tinggi untuk bias, timeframe eksekusi untuk entry. EMA20/50/200="+fmt(s.ema20)+"/"+fmt(s.ema50)+"/"+fmt(s.ema200)+", RSI14="+fmt(s.rsi)+", BB="+fmt(s.bbLower)+"/"+fmt(s.bbMid)+"/"+fmt(s.bbUpper)+", ATR14="+fmt(s.atr)+", S/R="+fmt(s.support)+"/"+fmt(s.resistance)+", Fib 38.2/50/61.8="+fmt(s.fib382)+"/"+fmt(s.fib50)+"/"+fmt(s.fib618)+", public news="+s.news.size()+". Confidence adalah skor diagnostik, bukan win-rate/probabilitas profit.";}
 private static String fmt(double x){return String.format(Locale.US,"%.5f",x);}
}