package com.mazkiplay.nusantara;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.content.*;import android.content.res.ColorStateList;import android.security.keystore.*;import android.util.Base64;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import org.json.*;

public class MainActivity extends Activity{
 private static final String ENDPOINT="https://openrouter.ai/api/v1/",ALIAS="nusantara_agent_key";
 private final int BG=Color.rgb(8,8,10),PANEL=Color.rgb(18,18,22),PANEL2=Color.rgb(27,27,33),TEXT=Color.rgb(245,245,247),MUTED=Color.rgb(155,155,165),ACCENT=Color.rgb(16,163,127);
 private LinearLayout root,messages;private EditText composer,keyInput;private TextView connectionStatus,modelStatus;private Spinner modelSpinner;private SharedPreferences prefs;private SecretKey secret;private final ArrayList<JSONObject> history=new ArrayList<>();private ExecutorService io=Executors.newCachedThreadPool();

 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);prefs=getSharedPreferences("nusantara_secure",0);secret=getKey();showChat();}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private TextView text(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextColor(TEXT);t.setTextSize(z);t.setPadding(dp(14),dp(9),dp(14),dp(9));t.setLineSpacing(0,1.12f);return t;}
 private TextView label(String s,float z){TextView t=text(s,z);t.setTextColor(MUTED);return t;}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setAllCaps(false);b.setBackgroundTintList(ColorStateList.valueOf(PANEL2));return b;}
 private void base(String title,boolean back){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(9),dp(8),dp(9),dp(8));setContentView(root);LinearLayout top=new LinearLayout(this);TextView brand=text(title,19);brand.setTypeface(null,1);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button b=button(back?"← Chat":"⚙ Settings");top.addView(b,new LinearLayout.LayoutParams(dp(105),dp(48)));root.addView(top);b.setOnClickListener(v->{if(back)showChat();else showSettings();});}
 private void nav(){LinearLayout n=new LinearLayout(this);Button c=button("◈ Chat"),f=button("📈 Forex Agent"),s=button("⚙ Settings");n.addView(c,new LinearLayout.LayoutParams(0,48,1));n.addView(f,new LinearLayout.LayoutParams(0,48,1));n.addView(s,new LinearLayout.LayoutParams(0,48,1));root.addView(n);c.setOnClickListener(v->showChat());f.setOnClickListener(v->showForex());s.setOnClickListener(v->showSettings());}

 private void showChat(){base("◈ NUSANTARA AGENT",false);nav();LinearLayout bar=new LinearLayout(this);TextView a=text("● READY",12);a.setTextColor(ACCENT);TextView m=text(prefs.getString("model","AUTO").isEmpty()?"AUTO":prefs.getString("model","AUTO"),10);m.setGravity(Gravity.RIGHT);m.setTextColor(MUTED);bar.addView(a,new LinearLayout.LayoutParams(0,-2,1));bar.addView(m,new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);
  ScrollView sc=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);sc.addView(messages);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
  if(history.isEmpty())addBubble(false,"NUSANTARA","Siap. OpenRouter BYO key ada di Settings. Untuk analisis forex, buka Forex Agent → pilih pair, mode, modal, risiko, lalu Analyze.");
  else for(JSONObject h:history)addBubble("user".equals(h.optString("role")),"user".equals(h.optString("role"))?"GUE":"NUSANTARA",h.optString("content"));
  LinearLayout tools=new LinearLayout(this);Button clear=button("＋ Baru");tools.addView(clear,new LinearLayout.LayoutParams(dp(70),dp(52)));composer=new EditText(this);composer.setHint("Message Nusantara Agent…");composer.setHintTextColor(MUTED);composer.setTextColor(TEXT);composer.setMaxLines(5);composer.setBackgroundColor(PANEL);tools.addView(composer,new LinearLayout.LayoutParams(0,dp(52),1));Button send=button("➤");tools.addView(send,new LinearLayout.LayoutParams(dp(58),dp(52)));root.addView(tools);clear.setOnClickListener(v->{history.clear();showChat();});send.setOnClickListener(v->sendMessage());}

 private void addBubble(boolean user,String who,String body){LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);TextView h=text(who,12);h.setTypeface(null,1);h.setTextColor(user?Color.rgb(120,190,255):ACCENT);TextView b=text(body,15);b.setBackgroundColor(user?Color.rgb(35,35,43):PANEL);b.setTextIsSelectable(true);w.addView(h);w.addView(b);Button pdf=button("📄 PDF");w.addView(pdf,new LinearLayout.LayoutParams(-2,40));pdf.setOnClickListener(v->savePdf(who,body));messages.addView(w,new LinearLayout.LayoutParams(-1,-2));}

 private void sendMessage(){String q=composer==null?"":composer.getText().toString().trim();if(q.isEmpty())return;composer.setText("");history.add(msg("user",q));addBubble(true,"GUE",q);addBubble(false,"NUSANTARA","⏳ Menyusun respons…");io.submit(()->{try{String k=loadKey();if(k.isEmpty())throw new Exception("API key belum tersimpan.");JSONObject body=new JSONObject();body.put("model",getModel());JSONArray a=new JSONArray();a.put(msg("system","You are Nusantara Agent, an Indonesian AI agent. Be precise, technical, practical and honest about uncertainty. Never invent live data. For trading, distinguish market facts from scenarios; never promise win rates or guaranteed profit."));for(JSONObject h:history)a.put(h);body.put("messages",a);body.put("temperature",0.4);body.put("stream",false);String raw=request("chat/completions",k,body.toString(),"POST");JSONObject o=new JSONObject(raw);String ans=o.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","");if(ans.isEmpty())throw new Exception(apiError(o));history.add(msg("assistant",ans));runOnUiThread(this::showChat);}catch(Exception e){history.add(msg("assistant","ERROR: "+e.getMessage()));runOnUiThread(this::showChat);}});}
 private JSONObject msg(String r,String c){JSONObject o=new JSONObject();try{o.put("role",r);o.put("content",c);}catch(Exception ignored){}return o;}
 private String getModel(){String s=prefs.getString("model","");return s.isEmpty()?"openai/gpt-5-mini":s;}

 private void showForex(){base("📈 FOREX AGENT",true);ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(5,8,5,24);
  box.addView(label("MULTI-FACTOR MARKET ANALYST • public data + technical engine + AI synthesis",12));
  EditText pair=new EditText(this);pair.setText("EUR/USD");pair.setHint("Pair, contoh EUR/USD");pair.setTextColor(TEXT);pair.setHintTextColor(MUTED);box.addView(pair,new LinearLayout.LayoutParams(-1,54));
  LinearLayout row=new LinearLayout(this);Spinner tf=new Spinner(this),style=new Spinner(this);tf.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"5m","15m","1h","4h","1d"}));style.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Scalping","Intraday","Swing"}));row.addView(tf,new LinearLayout.LayoutParams(0,54,1));row.addView(style,new LinearLayout.LayoutParams(0,54,1));box.addView(row);
  EditText capital=new EditText(this);capital.setText("1000000");capital.setHint("Modal akun (IDR)");capital.setInputType(2);capital.setTextColor(TEXT);box.addView(capital,new LinearLayout.LayoutParams(-1,54));
  EditText risk=new EditText(this);risk.setText("1");risk.setHint("Risk % per trade");risk.setInputType(2|8192);risk.setTextColor(TEXT);box.addView(risk,new LinearLayout.LayoutParams(-1,54));
  Button analyze=button("⚡ ANALYZE LIVE MARKET");box.addView(analyze,new LinearLayout.LayoutParams(-1,54));TextView status=label("Menunggu analisis…",13);box.addView(status);
  MarketChartView chart=new MarketChartView(this);box.addView(chart,new LinearLayout.LayoutParams(-1,dp(280)));TextView result=text("",13);result.setTextIsSelectable(true);box.addView(result);
  TextView news=text("",12);news.setTextColor(MUTED);box.addView(news);
  sc.addView(box);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
  analyze.setOnClickListener(v->{String p=pair.getText().toString().trim().toUpperCase(Locale.US).replace("-","/");String interval=tf.getSelectedItem().toString();String st=style.getSelectedItem().toString();double cap=parse(capital.getText().toString(),1000000),rp=parse(risk.getText().toString(),1);status.setText("⏳ Mengambil candle + news publik…");io.submit(()->{try{String yahooInterval=interval.equals("4h")?"1h":interval;ForexAgent.Snapshot x=ForexAgent.analyze(p,yahooInterval,st,cap,rp);runOnUiThread(()->{chart.setData(x.candles);status.setText("🟢 LIVE SNAPSHOT • "+x.asOf);String rr="SIGNAL: "+x.signal+"\nTrend: "+x.trend+"\nSetup: "+x.setup+"\n\nPrice: "+fmt(x.price)+"\nEntry: "+fmt(x.entry)+"\nSL: "+fmt(x.sl)+"\nTP1 (1:2): "+fmt(x.tp1)+"\nTP2 (1:3): "+fmt(x.tp2)+"\n\nRSI14: "+fmt(x.rsi)+"\nEMA20/50/200: "+fmt(x.ema20)+" / "+fmt(x.ema50)+" / "+fmt(x.ema200)+"\nBB Lower/Mid/Upper: "+fmt(x.bbLower)+" / "+fmt(x.bbMid)+" / "+fmt(x.bbUpper)+"\nATR14: "+fmt(x.atr)+"\nSupport/Resistance: "+fmt(x.support)+" / "+fmt(x.resistance)+"\nFib 38.2/50/61.8: "+fmt(x.fib382)+" / "+fmt(x.fib50)+" / "+fmt(x.fib618)+"\n\nRisk: "+fmt(x.riskPct)+"% | Position sizing proxy: "+fmt(x.positionUnits)+" units\nDiagnostic confidence: "+fmt(x.confidence)+" / 100\n\n"+x.rationale+"\n\nLayering: hanya pertimbangkan bertahap jika harga tetap berada dalam zona setup dan total risiko akun tidak bertambah melampaui batas yang ditetapkan.";result.setText(rr);StringBuilder nb=new StringBuilder("📰 PUBLIC NEWS ("+x.news.size()+")\n");for(ForexAgent.News n:x.news)nb.append("• ").append(n.title).append("\n");news.setText(nb.toString());});}catch(Exception e){runOnUiThread(()->status.setText("🔴 DATA ERROR: "+e.getMessage()));}});});
 }

 private double parse(String s,double d){try{return Double.parseDouble(s.replace(",","").trim());}catch(Exception e){return d;}}
 private String fmt(double x){return String.format(Locale.US,"%.5f",x);}

 private void showSettings(){base("⚙ SETTINGS",true);ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(6,8,6,24);box.addView(text("OpenRouter",24));box.addView(label("BYO key • Android Keystore encrypted",13));keyInput=new EditText(this);keyInput.setHint("sk-or-v1-…");keyInput.setTextColor(TEXT);keyInput.setHintTextColor(MUTED);keyInput.setSingleLine(true);keyInput.setInputType(129);String old=loadKey();if(!old.isEmpty())keyInput.setText(old);box.addView(keyInput,new LinearLayout.LayoutParams(-1,56));Button test=button("✓ TEST CONNECTION");box.addView(test,new LinearLayout.LayoutParams(-1,52));connectionStatus=label("⚪ NOT READY",15);box.addView(connectionStatus);modelStatus=label("Model catalog belum dimuat.",13);box.addView(modelStatus);modelSpinner=new Spinner(this);box.addView(modelSpinner,new LinearLayout.LayoutParams(-1,52));Button refresh=button("↻ REFRESH MODELS");box.addView(refresh,new LinearLayout.LayoutParams(-1,50));box.addView(label("Forex data: public market candles + public news RSS. Broker-specific LP/order-book tidak dipalsukan; adapter broker dapat ditambahkan untuk data depth yang benar-benar tersedia.",12));sc.addView(box);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));test.setOnClickListener(v->testConnection());refresh.setOnClickListener(v->discoverModels());if(!old.isEmpty())connectionStatus.setText("🟡 KEY TERSIMPAN");}
 private void testConnection(){String k=keyInput.getText().toString().trim();if(k.isEmpty()){connectionStatus.setText("🔴 API key kosong");return;}saveKey(k);connectionStatus.setText("🟡 CHECKING…");io.submit(()->{try{JSONObject o=new JSONObject(requestGet("models",k));JSONArray d=o.optJSONArray("data");if(d==null)throw new Exception("Respons models invalid");runOnUiThread(()->{connectionStatus.setText("🟢 READY — OpenRouter Connected");modelStatus.setText("✓ "+d.length()+" model");discoverModels();});}catch(Exception e){runOnUiThread(()->connectionStatus.setText("🔴 NOT READY — "+e.getMessage()));}});}
 private void discoverModels(){String k=loadKey();if(k.isEmpty()){modelStatus.setText("Masukkan API key.");return;}io.submit(()->{try{JSONArray a=new JSONObject(requestGet("models",k)).getJSONArray("data");ArrayList<String>l=new ArrayList<>();l.add("AUTO");for(int i=0;i<a.length();i++){String id=a.getJSONObject(i).optString("id","");if(!id.isEmpty())l.add(id);}runOnUiThread(()->{ArrayAdapter<String>ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,l);modelSpinner.setAdapter(ad);String cur=prefs.getString("model","");int pos=l.indexOf(cur);if(pos<0)pos=0;modelSpinner.setSelection(pos);modelSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int x,long id){prefs.edit().putString("model",l.get(x).equals("AUTO")?"":l.get(x)).apply();}public void onNothingSelected(AdapterView<?>p){}});modelStatus.setText("✓ "+l.size()+" model choices");});}catch(Exception e){runOnUiThread(()->modelStatus.setText("🔴 "+e.getMessage()));}});}
 private String request(String path,String k,String body,String method)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(ENDPOINT+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setRequestProperty("Authorization","Bearer "+k);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");c.setRequestProperty("HTTP-Referer","https://github.com/jambudio336-hue/Nusantara-Agent");c.setRequestProperty("X-Title","Nusantara Agent");if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String s=read(in);if(code<200||code>=300)throw new Exception("HTTP "+code+": "+compact(s));return s;}
 private String requestGet(String p,String k)throws Exception{return request(p,k,null,"GET");}private String read(InputStream in)throws Exception{if(in==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String z;while((z=r.readLine())!=null)s.append(z);return s.toString();}private String compact(String s){return s!=null&&s.length()>500?s.substring(0,500):s;}private String apiError(JSONObject o){JSONObject e=o.optJSONObject("error");return e==null?o.toString():e.optString("message","API error");}
 private SecretKey getKey(){try{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias(ALIAS)){KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,3).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return(SecretKey)k.getKey(ALIAS,null);}catch(Exception e){return null;}}
 private void saveKey(String s){try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(1,secret);prefs.edit().putString("key",Base64.encodeToString(c.getIV(),2)+"."+Base64.encodeToString(c.doFinal(s.getBytes(StandardCharsets.UTF_8)),2)).apply();}catch(Exception ignored){}}
 private String loadKey(){try{String z=prefs.getString("key","");int d=z.indexOf('.');if(d<0)return"";Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(2,secret,new GCMParameterSpec(128,Base64.decode(z.substring(0,d),2)));return new String(c.doFinal(Base64.decode(z.substring(d+1),2)),StandardCharsets.UTF_8);}catch(Exception e){return"";}}
 private void savePdf(String who,String body){try{PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=p.getCanvas();Paint q=new Paint(1);q.setTextSize(13);int y=40;for(String w:body.split(" ")){c.drawText(w,30,y,q);y+=16;if(y>800){d.finishPage(p);p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());c=p.getCanvas();y=40;}}d.finishPage(p);File f=new File(getExternalFilesDir(null),"Nusantara-"+System.currentTimeMillis()+".pdf");FileOutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();Toast.makeText(this,"PDF tersimpan",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"PDF error",Toast.LENGTH_SHORT).show();}}
 @Override protected void onDestroy(){super.onDestroy();io.shutdownNow();}
}