package com.mazkiplay.nusantara;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.pdf.PdfDocument;import android.content.*;import android.security.keystore.*;import android.util.Base64;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import org.json.*;

public class MainActivity extends Activity {
 LinearLayout root,chat; EditText input,key; TextView status,modelLabel; Spinner models; String endpoint="https://openrouter.ai/api/v1/"; android.content.SharedPreferences prefs; SecretKey secret;
 int red=Color.rgb(255,59,48), bg=Color.rgb(9,9,9), panel=Color.rgb(22,22,22);
 TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(sp);t.setPadding(16,12,16,12);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("secure",0);secret=getKey();build();}
 SecretKey getKey(){try{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias("nusantara")){KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("nusantara",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return ((KeyStore)ks).getKey("nusantara",null) instanceof SecretKey?(SecretKey)((KeyStore)ks).getKey("nusantara",null):null;}catch(Exception e){return null;}}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg); LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL); TextView title=tv("🇮🇩 NUSANTARA AGENT",20);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button set=btn("⚙");top.addView(set);root.addView(top);set.setOnClickListener(v->settings());
 TextView welcome=tv("Selamat datang di Terminal AI Agent Pekalongan Community\nby M4ZK1pL4y",15);root.addView(welcome); ScrollView sc=new ScrollView(this);chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);sc.addView(chat);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1)); LinearLayout bar=new LinearLayout(this);input=new EditText(this);input.setHint("Tulis pesan ke Nusantara…");input.setTextColor(Color.WHITE);input.setHintTextColor(Color.GRAY);bar.addView(input,new LinearLayout.LayoutParams(0,-2,1));Button send=btn("KIRIM");bar.addView(send);root.addView(bar);send.setOnClickListener(v->send());setContentView(root);}
 void add(String who,String text){TextView t=tv(who+"\n"+text,15);t.setBackgroundColor(panel);chat.addView(t);Button pdf=btn("📄 Simpan PDF");chat.addView(pdf);pdf.setOnClickListener(v->pdf(text));}
 void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;input.setText("");add("GUE",q);new Thread(()->{try{String k=load();if(k.isEmpty())throw new Exception("OpenRouter belum dikonfigurasi. Buka Settings.");String m=getSelectedModel();String body="{\"model\":"+JSONObject.quote(m)+",\"messages\":[{\"role\":\"user\",\"content\":"+JSONObject.quote(q)+"}]}";String out=request("chat/completions",k,body);JSONObject o=new JSONObject(out);String a=o.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","");runOnUiThread(()->add("NUSANTARA",a));}catch(Exception e){runOnUiThread(()->add("ERROR",e.getMessage()));}}).start();}
 String getSelectedModel(){if(models==null||models.getSelectedItem()==null)return "openai/gpt-4o-mini";return models.getSelectedItem().toString();}
 String request(String path,String k,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(endpoint+path).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setDoOutput(true);c.setRequestProperty("Authorization","Bearer "+k);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("HTTP-Referer","https://github.com/jambudio336-hue/Nusantara-Agent");c.setRequestProperty("X-Title","Nusantara Agent");c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String s=read(is);if(code<200||code>=300)throw new Exception("HTTP "+code+": "+s);return s;}
 String read(InputStream i)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(i));StringBuilder s=new StringBuilder();String x;while((x=r.readLine())!=null)s.append(x);return s.toString();}
 void settings(){root.removeAllViews();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(18,18,18,18);TextView h=tv("⚙ OpenRouter Settings",22);h.setTypeface(null,1);box.addView(h);key=new EditText(this);key.setHint("Paste sk-or-v1-…");key.setInputType(129);key.setTextColor(Color.WHITE);String old=load();if(!old.isEmpty())key.setText(old);box.addView(key);Button test=btn("TEST CONNECTION");box.addView(test);status=tv("⚪ NOT READY",16);box.addView(status);modelLabel=tv("Model",16);box.addView(modelLabel);models=new Spinner(this);box.addView(models);Button refresh=btn("REFRESH MODELS");box.addView(refresh);Button back=btn("← KEMBALI");box.addView(back);test.setOnClickListener(v->test());refresh.setOnClickListener(v->discover());back.setOnClickListener(v->{build();});setContentView(box);}
 void test(){String k=key.getText().toString().trim();if(k.isEmpty()){status.setText("🔴 NOT READY — API key kosong");return;}save(k);status.setText("🟡 CHECKING…");new Thread(()->{try{String s=requestGet("models",k);new JSONObject(s);runOnUiThread(()->{status.setText("🟢 READY — OpenRouter Connected");discover();});}catch(Exception e){runOnUiThread(()->status.setText("🔴 NOT READY — "+e.getMessage()));}}).start();}
 String requestGet(String path,String k)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(endpoint+path).openConnection();c.setRequestProperty("Authorization","Bearer "+k);c.setRequestProperty("Content-Type","application/json");int code=c.getResponseCode();InputStream is=code>=200&&code<300?c.getInputStream():c.getErrorStream();String s=read(is);if(code<200||code>=300)throw new Exception("HTTP "+code+": "+s);return s;}
 void discover(){new Thread(()->{try{String s=requestGet("models",load());JSONArray a=new JSONObject(s).getJSONArray("data");String[] ms=new String[Math.min(a.length(),100)+1];ms[0]="AUTO";for(int i=0;i<a.length()&&i<100;i++)ms[i+1]=a.getJSONObject(i).optString("id");runOnUiThread(()->{models.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ms));});}catch(Exception e){}}).start();}
 void pdf(String text){try{PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());android.graphics.Canvas c=p.getCanvas();android.graphics.Paint paint=new android.graphics.Paint();paint.setTextSize(14);int y=40;for(String line:text.split("\\n")){c.drawText(line,30,y,paint);y+=20;if(y>800){break;}}d.finishPage(p);File f=new File(getExternalFilesDir(null),"Nusantara-"+System.currentTimeMillis()+".pdf");FileOutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();Toast.makeText(this,"PDF tersimpan: "+f.getAbsolutePath(),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 void save(String s){try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,secret);byte[] iv=c.getIV(),enc=c.doFinal(s.getBytes(StandardCharsets.UTF_8));prefs.edit().putString("key",Base64.encodeToString(iv,2)+"."+Base64.encodeToString(enc,2)).apply();}catch(Exception e){}}
 String load(){try{String z=prefs.getString("key","");if(z.isEmpty())return "";String[] p=z.split("\\.");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,secret,new GCMParameterSpec(128,Base64.decode(p[0],2)));return new String(c.doFinal(Base64.decode(p[1],2)),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
}