package com.mazkiplay.nusantara;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.security.keystore.*;import android.util.Base64;import android.webkit.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import org.json.*;

public class MainActivity extends Activity{
 private static final String ENDPOINT="https://openrouter.ai/api/v1/",ALIAS="nusantara_agent_key";
 private WebView web; private android.content.SharedPreferences prefs; private SecretKey secret; private ExecutorService io=Executors.newCachedThreadPool();
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("secure",0);secret=getKey();web=new WebView(this);web.setBackgroundColor(0xff09090b);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(false);web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(final PermissionRequest r){runOnUiThread(()->r.grant(r.getResources()));}});web.addJavascriptInterface(new Bridge(),"Android");setContentView(web);requestPermissionsIfNeeded();web.loadUrl("file:///android_asset/index.html");}
 private void requestPermissionsIfNeeded(){if(Build.VERSION.SDK_INT>=23){ArrayList<String> p=new ArrayList<>();if(checkSelfPermission("android.permission.CAMERA")!=PackageManager.PERMISSION_GRANTED)p.add("android.permission.CAMERA");if(checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED)p.add("android.permission.RECORD_AUDIO");if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),77);}}
 private SecretKey getKey(){try{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias(ALIAS)){KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,3).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return(SecretKey)k.getKey(ALIAS,null);}catch(Exception e){return null;}}
 private void saveKey(String s){try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,secret);prefs.edit().putString("key",Base64.encodeToString(c.getIV(),2)+"."+Base64.encodeToString(c.doFinal(s.getBytes(StandardCharsets.UTF_8)),2)).apply();}catch(Exception ignored){}}
 private String loadKey(){try{String z=prefs.getString("key","");int d=z.indexOf('.');if(d<0)return"";Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,secret,new GCMParameterSpec(128,Base64.decode(z.substring(0,d),2)));return new String(c.doFinal(Base64.decode(z.substring(d+1),2)),StandardCharsets.UTF_8);}catch(Exception e){return"";}}
 private String request(String path,String key,String body,String method)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(ENDPOINT+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");c.setRequestProperty("HTTP-Referer","https://github.com/jambudio336-hue/Nusantara-Agent");c.setRequestProperty("X-Title","Nusantara Agent");if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String s=read(in);if(code<200||code>=300)throw new Exception("HTTP "+code+": "+compact(s));return s;}
 private String read(InputStream in)throws Exception{if(in==null)return"";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String z;while((z=r.readLine())!=null)s.append(z);return s.toString();}private String compact(String s){return s!=null&&s.length()>500?s.substring(0,500):s;}
 private void js(String fn,String arg){runOnUiThread(()->web.evaluateJavascript(fn+"("+JSONObject.quote(arg)+")",null));}
 public class Bridge{
  @JavascriptInterface public void saveKey(String k){if(k==null||k.trim().isEmpty()){js("onStatus","🔴 API key kosong");return;}saveKey(k.trim());js("onStatus","🟡 Testing OpenRouter…");io.submit(()->{try{request("models",k.trim(),null,"GET");js("onStatus","🟢 READY — OpenRouter Connected");}catch(Exception e){js("onStatus","🔴 NOT READY — "+e.getMessage());}});}
  @JavascriptInterface public void hasKey(){js("onStatus",loadKey().isEmpty()?"⚪ NOT READY":"🟡 KEY TERSIMPAN");}
  @JavascriptInterface public void setModel(String m){prefs.edit().putString("model",m).apply();}
  @JavascriptInterface public void models(){String k=loadKey();if(k.isEmpty()){js("onStatus","🔴 Masukkan API key dulu");return;}io.submit(()->{try{JSONArray d=new JSONObject(request("models",k,null,"GET")).getJSONArray("data");ArrayList<String> a=new ArrayList<>();a.add("openrouter/free");a.add("openrouter/auto");for(int i=0;i<d.length();i++){String id=d.getJSONObject(i).optString("id","");if(!id.isEmpty())a.add(id);}js("onModels",new JSONArray(a).toString());js("onStatus","🟢 "+a.size()+" model choices");}catch(Exception e){js("onStatus","🔴 "+e.getMessage());}});}
  @JavascriptInterface public void chat(String prompt,String id){String k=loadKey();if(k.isEmpty()){js("onAnswer",answer(id,"API key belum disimpan. Buka 🔑 Settings lalu Simpan & Test."));return;}io.submit(()->{try{String model=prefs.getString("model","openrouter/free");if(model.isEmpty())model="openrouter/free";JSONObject b=new JSONObject();b.put("model",model);b.put("temperature",0.4);JSONArray m=new JSONArray();m.put(new JSONObject().put("role","system").put("content","Anda adalah Nusantara Agent Pro. Jawab dalam Bahasa Indonesia secara presisi, teknis dan praktis. Untuk market/forex bedakan fakta live dari skenario dan jangan menjanjikan profit. Untuk tugas keamanan hanya bantu aktivitas berizin."));m.put(new JSONObject().put("role","user").put("content",prompt));b.put("messages",m);JSONObject o=new JSONObject(request("chat/completions",k,b.toString(),"POST"));String ans=o.optJSONArray("choices")!=null?o.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content",""):o.optJSONObject("error")!=null?o.getJSONObject("error").optString("message","API error"):"Tidak ada respons.";js("onAnswer",answer(id,ans));}catch(Exception e){js("onAnswer",answer(id,"ERROR: "+e.getMessage()));}});}
  private String answer(String id,String text){try{return new JSONObject().put("id",id).put("text",text).toString();}catch(Exception e){return "{\\"id\\":\\""+id+"\\",\\"text\\":\\"Error\\"}";}}
 }
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onDestroy(){io.shutdownNow();web.destroy();super.onDestroy();}
}