import 'package:flutter/material.dart';
import '../services/market_data.dart';
import '../services/market_engine.dart';
import '../services/openrouter.dart';
import '../models/market_candle.dart';
import '../widgets/candlestick_chart.dart';
import '../theme.dart';
class TradingScreen extends StatefulWidget{const TradingScreen({super.key});@override State<TradingScreen> createState()=>_TradingState();}
class _TradingState extends State<TradingScreen>{String symbol='EURUSD',tf='15m';List<MarketCandle> candles=[];Map<String,dynamic> a={};String? error;bool loading=false;String analysis='';
Future<void> load()async{setState(()=>loading=true);try{final d=await MarketData.candles(symbol,tf);if(!mounted)return;setState((){candles=d; a=MarketEngine.analyze(d); error=null;loading=false;});}catch(e){if(mounted)setState((){error=e.toString();loading=false;});}}
Future<void> _aiSignal() async { if(candles.length<30){setState(()=>analysis='Ambil candle aktual terlebih dahulu.');return;} final last=candles.last; final prompt='Analisis $symbol timeframe $tf dari data candle aktual berikut. Jangan mengarang fundamental atau berita; jika data Forex Factory tidak tersedia di prompt, nyatakan perlu verifikasi publik. Gabungkan EMA, RSI, Bollinger, ATR, support/resistance, market structure, liquidity/supply-demand, CHoCH/BOS, fakeout, dan multi-timeframe sebagai skenario. Beri BUY/SELL/WAIT, entry, SL, TP1-TP3, R:R, risiko, dan alasan. Ini riset edukasi, bukan nasihat finansial. Ringkasan teknikal internal: ${a.toString()}. Candle terakhir OHLC: ${last.open}, ${last.high}, ${last.low}, ${last.close}, volume ${last.volume}.'; setState(()=>analysis='Menganalisis teknikal dan konteks fundamental...'); final result=await OpenRouter.chat([{'role':'user','content':prompt}]); if(mounted)setState(()=>analysis=result); }
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('$symbol $tf'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:ListView(padding:const EdgeInsets.all(12),children:[SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:MarketData.forex.map((s)=>Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(s),selected:s==symbol,onSelected:(_){setState(()=>symbol=s);load();}))).toList())),const SizedBox(height:8),Row(children:[Expanded(child:DropdownButtonFormField<String>(value:tf,items:MarketData.timeframes.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null){setState(()=>tf=x);load();}},decoration:const InputDecoration(labelText:'Timeframe'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:loading?null:_aiSignal,icon:const Icon(Icons.auto_awesome),label:const Text('AI SIGNAL')))]),const SizedBox(height:8),SizedBox(height:380,child:CandleChart(candles:candles,entry:null,sl:null,tp:null)),if(loading)const LinearProgressIndicator(),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),if(analysis.isNotEmpty)Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:MzTheme.card,borderRadius:BorderRadius.circular(16)),child:Text(analysis,style:const TextStyle(color:Colors.white70,height:1.45))),Container(margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:MzTheme.card,borderRadius:BorderRadius.circular(16)),child:const Text('Chart memakai provider market-data yang dikonfigurasi pengguna. Fundamental Forex Factory tidak dianggap tersedia kecuali benar-benar diterima dari sumber publik; signal bukan nasihat finansial.',style:TextStyle(color:Colors.white70))) ]));}
class TradeIntelligenceHub extends StatelessWidget{const TradeIntelligenceHub({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('MAZKIPLAY TRADE')),body:ListView(padding:const EdgeInsets.all(12),children:[ListTile(title:const Text('Market Radar'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const TradingScreen())))]));}
