import 'dart:async';
import 'package:flutter/material.dart';
import '../models/market_candle.dart';
import '../services/market_data.dart';
import '../services/market_engine.dart';
import '../widgets/candlestick_chart.dart';
import '../theme.dart';
import '../services/storage.dart';
class TradingScreen extends StatefulWidget { const TradingScreen({super.key}); @override State<TradingScreen> createState()=>_TradingScreenState(); }
class _TradingScreenState extends State<TradingScreen> { String symbol='EURUSD', tf='15m'; List<MarketCandle> candles=[]; Map<String,dynamic> a={}; bool loading=false; String? error; StreamSubscription? sub;
 @override void dispose(){sub?.cancel();super.dispose();}
 Future<void> load(){ sub?.cancel(); setState(()=>loading=true); return Future(() async { try { final data=await MarketData.candles(symbol,tf); if(!mounted)return; setState(()=>{candles=data,a=MarketEngine.analyze(data),loading=false,error=null}); } catch(e){if(mounted)setState(()=>{loading=false,error=e.toString()});} }); }
 void startLive(){sub?.cancel(); setState(()=>loading=true); sub=MarketData.polling(symbol,tf).listen((data){if(mounted)setState(()=>{candles=data,a=MarketEngine.analyze(data),loading=false,error=null});},onError:(e){if(mounted)setState(()=>{loading=false,error=e.toString()});});}
 @override Widget build(BuildContext context){ final signal=a['signal']?.toString()??'WAIT'; final score=a['score']?.toString()??'--'; return Scaffold(backgroundColor:const Color(0xFF080A10), appBar:AppBar(title:Text(symbol+'  '+tf),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>_FullChart(candles:candles,a:a))),icon:const Icon(Icons.fullscreen))]), body:OrientationBuilder(builder:(context,o){final landscape=o==Orientation.landscape; return Padding(padding:const EdgeInsets.all(10),child:Column(children:[_selector(),const SizedBox(height:8),Expanded(child:landscape?_landscape(signal,score):_portrait(signal,score))]));}));}
 Widget _selector()=>SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[...MarketData.forex,...MarketData.crypto].map((s)=>Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(s),selected:s==symbol,onSelected:(_){setState(()=>symbol=s);load();}))).toList()..addAll(MarketData.timeframes.map((t)=>Padding(padding:const EdgeInsets.only(right:5),child:ChoiceChip(label:Text(t),selected:t==tf,onSelected:(_){setState(()=>tf=t);load();}))))));
 Widget _chart()=>Container(decoration:BoxDecoration(color:const Color(0xFF0D111A),borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.white10)),child:CandleChart(candles:candles,entry:a['price'],sl:a['signal']=='SELL'?(a['price']??0)+((a['atr']??0)*1.5):null,tp:a['signal']=='SELL'?(a['price']??0)-((a['atr']??0)*3):null));
 Widget _panel(String signal,String score)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:MzTheme.card,borderRadius:BorderRadius.circular(16)),child:Wrap(spacing:18,runSpacing:10,children:[Text('LIVE  ●',style:TextStyle(color:Colors.greenAccent,fontWeight:FontWeight.bold)),Text('SIGNAL  '+signal,style:TextStyle(color:signal=='BUY'?Colors.greenAccent:signal=='SELL'?Colors.redAccent:Colors.amberAccent,fontWeight:FontWeight.w900)),Text('SCORE  '+score+'/100'),Text('RSI  '+(a['rsi']?.toStringAsFixed(1)??'--')),Text('EMA20  '+(a['ema20']?.toStringAsFixed(5)??'--')),Text('EMA50  '+(a['ema50']?.toStringAsFixed(5)??'--')),Text('ATR  '+(a['atr']?.toStringAsFixed(5)??'--'))]));
 Widget _portrait(String s,String score)=>Column(children:[Expanded(child:_chart()),const SizedBox(height:8),_panel(s,score),const SizedBox(height:8),Align(alignment:Alignment.centerLeft,child:Text(error??'Technical engine • Support/Resistance • Risk overlay',style:const TextStyle(color:Colors.white54,fontSize:11)))]);
 Widget _landscape(String s,String score)=>Row(children:[Expanded(flex:3,child:_chart()),const SizedBox(width:10),Expanded(flex:1,child:SingleChildScrollView(child:_panel(s,score)))]);
}
class _FullChart extends StatelessWidget { final List<MarketCandle> candles; final Map<String,dynamic> a; const _FullChart({required this.candles,required this.a}); @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(title:const Text('FULLSCREEN CHART')),body:CandleChart(candles:candles,entry:a['price'],sl:a['signal']=='SELL'?(a['price']??0)+((a['atr']??0)*1.5):null,tp:a['signal']=='SELL'?(a['price']??0)-((a['atr']??0)*3):null)); }